import_logs.py
tests/logs/iis_custom.log
tests/tests.py

Handle extra whitespace in W3C extended logs, including in between comment lines and in Fields: line.

---

import_logs.py

As title.
Tests are included w/ https://github.com/piwik/piwik/pull/8644.

Use bulk tracking indices to display the lines of logs that were considered invalid by the Piwik tracker.

---

import_logs.py

Whenever generation_time_milli is 0 ( or more accurately, `0.0000`), the json returned will be interpreted as a *`string`* and not a *`float`*.
Forcing the cast fixes the issue.
Happened to me while serving static html pages.

Issue when generation_time_milli is 0

---

import_logs.py

As title. Fix is simple.
Fixes #16

Convert hex escapes in malformed JSON to unicode escapes to workaround nginx bug.

---

README.md

nginx 1.10.0's default access log format can be parsed with `ncsa_extended`. `common_complete` fails, and `common` does not contain referer and user agent.

Mention correct nginx access log format

---

import_logs.py

Since pingdom is a popular service I thought it might be worth having on the
bot list. I won't be offended if the suggestion is to use _bot_ instead as it
would handle a wider variety of services.

Add pingdom to EXCLUDED_USER_AGENTS list

---

import_logs.py

UA from logs are transformed into lowercase before comparison to
excluded UA. Therefore excluded UA must be in lowercase.
Signed-off-by: Kevin Decherf <kevin@kdecherf.com>

Fix Pingdom bot exclusion

---

README.md

When logging multiple virtual hosts we need to use the
`common_complete` log format it is defined as
`host + ncsa_extended`.

Fix NGINX related documentation

---

README.md
import_logs.py

took me 30min to figure this out as it wasn't documented

Clarify that * character must be used in --exclude-path to exclude a path matching a pattern

---

import_logs.py

fast, probably ugly workaround fix for #126 due to Host regex can't be empty or logimport hangs in a loop forever.
a better long term solution would be to trigger invalidate/ignore empty host lines and throw an invalid log line exception and just ignore those lines probably, but due to lack of python knowledge, i can't implement such case.

Fixes #126

---

README.md

Probably every modern python-dev knows how that nosetests stuff works, but mentioning of `run_tests.sh` in README would have saved me some seconds.

Mention tests/run_tests.sh script

---

import_logs.py
tests/logs/ovh.log
tests/tests.py

OVH shared hosting are providing raw logs in a format which is a bit different from the common_vhost format. Actually, the host is not before, but after the IP address.
So I added a regex for this specific case, for my own needs. If you think it's interesting, just feel free to merge it...
And thank you for your contribution to libre software!

Add OVH log format

---

import_logs.py

As it just popped up in piwik/piwik#11943 the log importer throws a potentially misleading stacktrace at you if the token authentication cannot be fetched when using login/password.
This happens because the calls to the API require the config object for retry handling. But if the call is made to fetch the authentication token this object is not yet available. So if the call fails for whatever reason the script aborts with a `NameError`.
The real error is still at the very top of the output but some people might look at only the last line (`NameError: global name 'config' is not defined`) and miss the real error.
With this patch the fallback is made to the default values for retry count and delay.

Prevent NameError during configuration phase

---

import_logs.py

Currently the invalid line is reported even for lines that are still imported.
Here is an example of the issue. The log file has 590887 lines, and 584895 were imported successfully. But the output also reports  594622 lines which is not true.
```
Logs import summary
-------------------
584895 requests imported successfully
0 requests were downloads
596860 requests ignored:
0 HTTP errors
0 HTTP redirects
594622 invalid log lines
2147 filtered log lines
0 requests did not match any known site
0 requests did not match any --hostname
91 requests done by bots, search engines...
0 requests to static resources (css, js, images, ico, ttf...)
0 requests to file downloads did not match any --download-extensions
Website import summary
----------------------
584895 requests imported to 1 sites
1 …
```

Only issue an invalid line status, when the line was really invalid and skipped

---

import_logs.py

Right now the log importer only works for Python 2. Until `$someone` provides a pull request like the one done for the python api (https://github.com/piwik/piwik-python-api/commit/e96299b830a39961e0c91e23bb7d4ad7ef85e24e) this patch provides an early warning to improve the experience for users with an unknown/managed environment. (see https://github.com/piwik/piwik-log-analytics/issues/192 for example)
Please note that I have only tested it with Python 2.7. Python 2.6 should contain all included syntax changes ([Python 2.6 Changelog](https://docs.python.org/2/whatsnew/2.6.html)).

Abort with warning when using Python 3

---

import_logs.py
tests/tests.py

Adds a new option `--track-http-method` to enable tracking of http method as page cvar.
fixes #25

Adds option to enable tracking of HTTP-method as page custom variable

---

import_logs.py

This option allows a user to ignore certificate validation problems when connecting to the Piwik server. This is useful when the server uses a self-signed or otherwise invalid certificate, but obviously should only be used when the connection can be trusted.
This PR should resolve #42 and #138.
This PR implements the new --accept-invalid-ssl-certificate option in a slightly different way than suggested in #42: Instead of messing around with internal functions of the `ssl` module, it only uses public API by creating an SSL context using the default options, disabling validation for this context instance, and then passing this context to `urllib2` (or more precisely `HTTPSHandler`). This is also the way suggested by the Python documentation and - in contrast to the way suggested in #42 - …

Add --accept-invalid-ssl-certificate option.

---

import_logs.py
tests/tests.py

Changes:
* Added the `--add-to-date` option which takes a number of seconds. This is value added to every tracker request's date so the requests seem newer then the dates in the logs.
* Added the `--request-suffix` option which appends a string to the query string for requests sent to Matomo. This can be used to mark requests that the log importer sends, so they can be identified in, for example, a plugin event. For example, I could add `reset=1` to every request so my `Tracker.getDatabaseConfig` event handler will know when we're in a tracker request made by that specific log importer execution.

Adding two options --add-to-date & --request-suffix

---

import_logs.py
tests/tests.py

PHP supports sending/parsing multidimensional arrays in the URL, eg:
`param[key1][key2][] = 12`
which would be parsed as:
```
[
'key1' => [
'key2' => [
12,
],
],
]
```
Python does not, so if you're replaying logs for a plugin that uses multidimensional array tracker query parameters, the replay will fail.
This fixes the issue by converting such parameters manually. Tried also to convert the parsed query string back into a query string (which would have been far simpler), but python 2 has trouble with converting querystrings with unicode.
Note: I tried converting the string parts to unicode before calling `urllib.urlencode()` (as suggested here: https://stackoverflow.com/questions/6480723/urllib-urlencode-doesnt-like-unicode-values-how-about-this-workaround), but that results in odd test …

Convert multidimensional query parameter args in URLs correctly

---

import_logs.py

Also add new `--tracker-endpoint-path` to allow tracking to custom tracking endpoint.
Fixes #224

By default support replaying tracking requests to both piwik.php and matomo.php.

---

README.md

The readme shows an example crontab rule to "import your logs automatically each day (at 0:01)". However, there is a mistake in the rule below - "0 1 * * *" is actually 1:00, not 0:01.

fixed example crontab rule in the readme

---

import_logs.py

The `robots.txt` file is listed in the `STATIC_EXTENSIONS` list, however the entries from this list are only compared against `hit.extension` - which in case of `robots.txt` will be `txt`. So the result is that this file is not excluded from log entries and appears on the Downloads report.
This PR adds a second list of static files with full filenames (with just this one file at the moment) that's instead compared with the whole last path element of the URL.

fixed robots.txt not being counted as static file

---

README.md

When using this script with a Matomo install on a different
machine, one must include the --token-auth=<SECRET> parameter to
successfully send the logs to Matomo. This was not previously
mentioned in this particular section and is easy to overlook when
not reading about the other methods described herein.
I personally spent way too much time trying to solve this issue until
another person on irc pointed out this flag. I figured this minor edit
will save someone else from the confusion and extra research.

Clarified usage of --token-auth=<SECRET>

---

import_logs.py
tests/logs/splitted_date_and_time.log
tests/tests.py

currently date and time needs to be directly behind each other, as otherwise the regex would break.
This change allows to have date and time somewhere in there field order, and also allows to have it wrapped in `"`.
might help with #179

Improve regex for date and time in w3c formats

---

import_logs.py

refs https://github.com/matomo-org/matomo/issues/6559
Will be needed in 4.x since we remove getTokenAuth method.
We need to wait for other PR to be merged before merging this

Compatibility with app specific tokens

---

import_logs.py
tests/tests.py

There are two places in the code which apply a timezone difference to a parsed date: when parsing command line arguments (`Configuration._set_date`) and when processing a hit (`Parser.parse`). They do that in a rather hacky way: the timezone is parsed as a number and then the difference is set to be `number / 100` hours.
This kind of works... except it assumes that timezones can only be at full integer intervals, and that's not true. There are several non-integer timezones, including in such important countries as India (+05:30) or Iran (+03:30). In that case, `"0530"` is interpreted as 5.3 hours ahead of UTC instead of 5.5...
For example, with such log line:
`1.2.3.4 - - [29/Nov/2018:15:30:00 +0530] "GET / HTTP/1.1" 200 6355 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) …

Fix timezone calculation for non-integer timezones
