matomo-org/matomo-log-analytics

- import_logs.py
Includes the following changes:
* Do not truncate responses received from server when printing error messages.
* Add response + HTTP error code to error message if HTTP error exception is caught. The error message will look like, '404 Not Found: ... piwik response ...' instead of 'Not Found'.
* Output redirects in debug logs for easier debugging. With --debug supplied, redirects sent by Piwik will appear in the log output.
@quba Can you confirm this will help you debug log importer issues?
@mattab Can you do a quick review?
> Improve ability to debug w/ various added diagnostic & debug messages/improvements.

- import_logs.py
Even if it is not a very common image format, mod_pagespeed creates
files in WebP format out of PNG or JPEG images.
> Add webp to STATIC_EXTENSIONS.

- import_logs.py
> Add --debug-tracker and --debug-request-limit options to help users and maintainers debug tracking issues

- .travis.yml
- README.md
As title.
@mattab I do not have enough permissions to enable the build on travis, can you enable it so I can test & merge this PR?
Fixes #48
> Add initial .travis.yml for running python tests.

- import_logs.py
fixes #97 
We should merge https://github.com/piwik/piwik/pull/8677/files after merging this one
> Make sure to always apply site_id if specified via option, even when --replay-tracking is used

- import_logs.py
Pull request from patch https://issues.piwik.org/3757.
ref #111
> Avoid Python stdin buffering

- README.md
- import_logs.py
Added ability to use Basic access authentication.
> Added basic auth

- import_logs.py
- tests/logs/shoutcast.log
- tests/tests.py
changes proposed by @entropywaves 
fixes #114
> Adds support for shoutcast

- import_logs.py
refs https://github.com/piwik/piwik/pull/10009/files
refs piwik/piwik#8458
> Make sure to always request all sites etc as in Piwik 3 there will be the default limit of 100 applied eg to SitesManager.getAllSites

- import_logs.py
- tests/logs/elb.log
- tests/tests.py
> Adds support for ELB log files

- import_logs.py
fixes https://github.com/piwik/piwik-log-analytics/issues/142
> Fix IOError: [Errno 29] Illegal seek

- import_logs.py
* Add woff2 as static extension
* Add flac, json, rtf and webm as download extensions
> Add new static and download extensions

- import_logs.py
Relates to https://github.com/piwik/piwik-log-analytics/issues/128
> adding option to provide separate url for API

- import_logs.py
https://github.com/piwik/piwik/issues/8566
> Deprecate JSON2 to use JSON 

- import_logs.py
Reverts piwik/piwik-log-analytics#160
https://github.com/piwik/piwik/pull/10928/files 
https://github.com/piwik/piwik/issues/8566
> Revert "Deprecate JSON2 to use JSON "

- README.md
> Fix nginx acess_log directive

- LEGALNOTICE
- LICENSE.txt
- README.md
Note that I am NOT the copyright owner or have any affiliation with the
piwik project.  This commit and the resulting PR were made informed by
aforementioned issue (#172) and the fact that the 'main' piwik git
repository includes this very repository and does not state
licence/copyright/trademark exceptions.  This commit is a pure proposal.
> Proposal to include license information via #172.

- CONTRIBUTING.md
- LEGALNOTICE
- import_logs.py
(sorry that I have to make multiple commits, but the Github web interface doesn't seem to allow multiple file edits in one commit)
> HTTP to HTTPS

- import_logs.py
> gracefully handle ValueError for generation time

- import_logs.py
- tests/tests.py
Refs https://github.com/piwik/piwik-log-analytics/issues/194
Refs https://github.com/piwik/piwik-log-analytics/issues/193
> Allow filtering logs by host & datetime

- import_logs.py
This fixes a regression introduced with PR #199.
The `context" parameter of the `urllib2.HTTPSHandler` constructor was only introduced in Python 2.7.9, so we cannot pass a specific SSL context in older Python versions. Luckily, we do not have to either because Python before 2.7.9 did not validate remote certificates anyway, so the behavior specified by the `--accept-invalid-ssl-certificate` option is actually the default when running
on these versions of Python.
> Make code compatible with Python <=2.7.8.

- import_logs.py
This fixes the problem discussed in #200. The `_get_token_auth` method in the `Configuration` class may use the `piwik` object which depends on the `config` object being present. This means that the `_get_token_auth` method must not be called from the `Configuration` contructor, but only after the `config` object has been created.
> Run _get_token_auth after config object is initialized.

- LEGALNOTICE
- README.md
- import_logs.py
https://matomo.org/blog/2018/01/piwik-is-now-matomo/
> Piwik is now Matomo

- import_logs.py
Signed-off-by: Samuele Kaplun <kaplun@protonmail.com>
> Linting code

- import_logs.py
relates https://github.com/matomo-org/matomo/pull/13192
> Use --matomo-domain instead of --piwik-domain

- README.md
- import_logs.py
- tests/logs/haproxy.log
- tests/tests.py
See https://forum.matomo.org/t/regex-fuer-haproxy/29959 for some background (in german).
> Add haproxy log format
